pull_request_rules:
  - name: Automatic merge on approval by helight
    conditions:
      - "approved-reviews-by=helight"
      - "#approved-reviews-by>=1"
      - base=master
    actions:
      merge:
        method: merge
