# This is a basic workflow to help you get started with Actions

name: sshcd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: SSH and SCP Setup
        # You may pin to the exact commit or the version.
        # uses: alinz/ssh-scp-action@8b390e33129b613ef0f72edfc1e325ff7fa3b5cf
        uses: alinz/ssh-scp-action@v0.1.1
        with:
          # ssh remote host
          host: 47.102.146.96 # optional
          # ssh remote port
          port: 22 # optional, default is 22
          # ssh user
          user: root # optional
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: -----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAq0fnBhbfSbY6O7XwVYatB+bqlDC/4MchI2RGb1P/vn8vLJeN
+1uYTU0yCn8R9WSXZkQssWjuRNPRY5IfCoP+FLi8Kayo9Sd0P+r6UzL3rWp9hwmg
5Ci7HGvb7DYqjTU+U5CyK7nGq7Sk7uM24/t2ex/JuaOalKOCUafGWfiYtOKe6Nfb
ugEeuRoymrepeEIFw2/CqJ9qc9FmjnYYAUDo/FYJRIxa/ch1WhbPIwWTO5hdSz14
fk0fc6yx5d+7LCqTEtk3k09uiZU8CEr2kY5AHhaEaiFPmd+9elq3dg1X+vLe+SlR
DgqB8737CR2LZ9mJxfjA+8fxX2Wy4OAgC9SeZwIDAQABAoIBADLujqQg6QTiSy62
S2EjSxCuedLXLDeK/y+nAcrZD5N1/nEkH/Q+qGtUKS013AE8iEjAvQmESlXtJraV
HOXjmgpPZKR/0z4THV5kYUucPEo1AF7HXjB6bClnaV40PTMAQihXPqQB+jHU5baj
mg7xF6pFKZcqLy1D8dyWJ0VZxw8CV8kbGuEx3KlNC+DOE2cHFMgFt4YcTinvi9rw
CQRduYpcd8cXpKEw8cD/FuOhCy2F8dVpfq9iErXNW6Rm4xeeyXF6UfazBBiVHMd4
yqARpohoT/ebS631frOUCBlm4h07bfTNts1Frs8a/4RTi60fLK3LoOoo+EWwV91G
/Rj3EAECgYEA3MQoRAf4xSEH0mRbwrBmtlfktne7wLLyPLB6rhZP22qcGT5Es3YT
5CP+otPxczMlrXeCOCbyTGpY7+oKoxTxftleZpLZE4iTmu17OcDTw0Zj8pUUbR6i
mKJlFJpEtFcthw1xCYamWGkgOllXcrs6s79ynEpsnUOo9ALY3Tm3PsECgYEAxp3s
En1R8PzUuZE8h4B3vVs4qavLb6lckLfIf4Iu36TGGZfxU41Ol0fy3hYD9Pb8/n7h
PX4En3BQlgho9ns+h5w3F9G8n8py2KMlQOcOeSMq5KT7L7TQGqK/d2KF3FWdrrjp
usYSPklU1o3k/i7KNvVj5p0MsGUv9Oo74UwszycCgYEAioCWMng93o7mdVx5JR++
kM97se5UYITj7KdbkDR3TVUJMd0bBOwjdpIOguEtLfT8wmOj0s68XKyrt3jBy6as
C8UbsIaYoeShliU/lfAf6vcSZXKaKgt6PwBDIjXWvL2k1oHcVPmhCv6JNZIvhs9n
+LU3lk4q7k8whEX1AHXhPQECgYA3tKE6ilWKHo9XQInWg0ySGlypEdrsBXdFy5X7
VTrqVN+O3BO+WFqbiX1vloMjmIZapqFrysVnJmwjuFYgE271P/Yfwx6BPpm5cwCG
1Ic1qIxmNnOQ7MiVP+ItjL94jba9A3XigZ0qRQz7ZC6+r8bdZTPQwWmGq8qoiW2k
AeZrbwKBgGF14yUDqwdKdKD5HCAlnbfFTB1x63fdxE+pH7MuSChyYQxuinrwc2pQ
rTIaaC7VDzmp4n4MeoHSJKIL6JsD1WVL5BvLWJ0L5jIJWA6XqBgpGk9dCTnJ55uz
umqRRdtN8oYF4euq28yqifGkJq2RqIdYcrPzq5y231Xyh+Yv7Qnk
-----END RSA PRIVATE KEY----- # optional
          # execute commands before SCP
          ssh_before: ls # optional
          # scp local and remote
          ssh_after: pwd # optional
